.DEFAULT_GOAL := run

init:
	pipenv --three install
	pipenv shell

analyze:
	flake8 ./src

run_tests:
	pytest --cov=src test/solution/

# comand line example: make run JOB_NAME=pi CONF_PATH=/your/path/pyspark-project-template/src/solution
run:
	# cleanup
	find . -name '__pycache__' | xargs rm -rf
	#rm -f solution.zip

	# create the zip
	cd src/ && zip -r ../solution.zip solution/

  # run the job
	spark-submit --py-files solution.zip src/main.py --job $(JOB_NAME) --res-path $(CONF_PATH)